// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package tutorial

import (
	"context"
	"database/sql"
)

const getWordsByTitle = `-- name: GetWordsByTitle :many
select WORDS.stem, WORDS.word, BOOK_INFO.title, LOOKUPS.usage
from LOOKUPS left join WORDS
on WORDS.id = LOOKUPS.word_key
left join BOOK_INFO
on BOOK_INFO.id = LOOKUPS.book_key
order by WORDS.stem, LOOKUPS.timestamp
`

type GetWordsByTitleRow struct {
	Stem  sql.NullString
	Word  sql.NullString
	Title sql.NullString
	Usage sql.NullString
}

// where BOOK_INFO.title = 'Personal History'
func (q *Queries) GetWordsByTitle(ctx context.Context) ([]GetWordsByTitleRow, error) {
	rows, err := q.db.QueryContext(ctx, getWordsByTitle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWordsByTitleRow
	for rows.Next() {
		var i GetWordsByTitleRow
		if err := rows.Scan(
			&i.Stem,
			&i.Word,
			&i.Title,
			&i.Usage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
